### ISSUE TITLE
Hugin Panorama

### ISSUE THREAD

**Issue by ghost** [guettli/panorama#1]
Hi,
I was wondering how works your python script, which runs Hugin. But, i couldn't. Would you show me how to run it? And explain a bit please. Thank you! Also, is it possible to make hdr image with it?

**Comment by guettli** [comment]
What happens, if you use it like this:

```
create-panorama-from-jpg-files-in-directory file_containing_jpg_files
```

See the usage page?

Please post tracebacks if you get them.

**Comment by guettli** [comment]
@RABEHAJA-STEVENS did it work for you? I love feedback.

I close it today. If you have a question, please reopen the issue.
